### ISSUE TITLE
Doesn't suspend properly on android

### ISSUE THREAD

**Issue by szalapski** [excaliburjs/sweep#1] opened 2014-12-14 23:17 UTC
After I exit the game, the audio continues to play and my battery drains.

**Comment by alanag13** [comment] 2014-12-14 23:24
@eonarheim called this out I know, the issue isn't unique to android -- In any browser sound continues to play when you switch the tabs; it's actually an issue with Excalibur (the game engine) rather than with the game itself. @eonarheim, is there an issue on the Excalibur repo to fix this? It sounds like we would just have to hook in to window.onblur / window.onfocus events to pause/resume audio.

@szalapski, as an unfortunately suboptimal workaround just closing the browser window when you're done will stop the drainage.

**Comment by kamranayub** [comment] 2014-12-14 23:28
Erik was working on this yesterday, he should have an update

-----Original Message-----

**Comment by eonarheim** [comment] 2014-12-15 00:21
Yah, this is a defect across all platforms. We currently have an issue in Excalibur #383 to address this.

The reason audio keeps playing is that it is not tied to the ex game loop it relies on a separate mechanism. The ex.Sound type needs to be wired in and we need to add the ability to receive engine events.  I've almost got this fixed using the blur/focus mechanism, but I'm looking into the new visibility api for a more robust determination of tab visibility.

**Comment by alanag13** [comment] 2015-01-03 08:46
The sound is properly suspended now, closing

**Closed as completed by alanag13** 2015-01-03 08:46 UTC
